### ISSUE TITLE
Problem running on Windows

### ISSUE THREAD

**Issue by gleporeNARA** [tballison/tika-gui-v2#119]
Getting an error "Windows cannot find 'jre/bin/java'" when running the v2 tika-gui.bat. The Linux version runs correctly. Java is installed, and the Release version runs.

**Comment by tballison** [comment]
Is this v1.0.0-ALPHA4?  If so, do you see that there is, in fact, a java at jre/bin/java relative to the .bat file?

**Comment by gleporeNARA** [comment]
tika-gui-v2-main, I just downloaded the Zip from GitHub. There is no java near the .bat file (which I put in Downloads). I was looking for a .jar file in the download somewhere to run directly, but no luck.

**Comment by tballison** [comment]
<img width="451" alt="Screenshot 2023-03-28 at 2 35 55 PM" src="https://user-images.githubusercontent.com/6739646/228335201-6b01295f-e684-41d3-9bca-a50a12b8cb51.png">
This Zip?

**Comment by gleporeNARA** [comment]
Yes.

**Comment by tballison** [comment]
If so, that's just the source code.  You'd have to build it and run the release locally to get all of the java stuff and jars where they belong.

The release zips for the latest release are here: https://github.com/tballison/tika-gui-v2/releases/tag/v1.0.0-ALPHA4 One per OS supported.

**Comment by tballison** [comment]
If there's enough new stuff for another release, I can make dependency upgrades and then push the release.

I was hoping to fix the sqlite stuff and the race condition in the UI before then.

**Comment by gleporeNARA** [comment]
Shoot, I knew that. My bad. I've previously used the releases but when I saw the version 2 tag I got excited. No worries about a new version if the changes don't warrant it.
