### ISSUE TITLE
overlapping fields

### ISSUE THREAD

**Issue by THausherr** [tballison/tika-gui-v2#54]
The text field and the button overlap if the text is too long. IMHO the text field should be limited.
![grafik](https://user-images.githubusercontent.com/6665575/201189998-4b3cab4e-b2d4-40af-8cac-4d22bbd763d3.png)
(I configured the output to be the bin directory)

Nice tool!

**Comment by tballison** [comment]
I said it was victory if the window opened! LOL..

**Comment by THausherr** [comment]
Not only that, it also started to mass-extract files and show a nice pie image! 👍

**Comment by tballison** [comment]
The joke is that I chose javafx so that I wouldn't have to worry about different browsers.  The diffs across operating systems and monitor sizes however...
